#!/bin/bash

pre=/usr/local


function CheckEnv() {

    local one=$1
    local oldval="${!one}"

    [ -n "$2" ] || exit 1

    if ! echo "${oldval}" | grep -q "$2" ; then
        if [ -n "${oldval}" ] ; then
            set -x
            export $1="${2}:${oldval}"
            set +x
        else
            set -x
            export $1="${2}"
            set +x
        fi
    fi
}


#CheckEnv PYTHONPATH "${pre}/lib/python3.8/site-packages"
CheckEnv PYTHONPATH "${pre}/lib/python3.9/site-packages"
CheckEnv LD_LIBRARY_PATH "${pre}/lib"
CheckEnv GRC_BLOCKS_PATH "${pre}/share/gnuradio/grc/blocks"




[ -n "$_JUST_PATHS_" ] && return


if [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then

    cat << EOF

      Usage: $0 PROGRAM [ARGS]

    So GNUradio can find its' python modules:
    Run PROGRAM with PYTHONPATH set to:

    $PYTHONPATH

    LD_LIBRARY_PATH set to:

    $LD_LIBRARY_PATH

    and GRC_BLOCKS_PATH set to:

    $GRC_BLOCKS_PATH

EOF

    exit 1
fi


if [ -n "$*" ] ; then
    set -x
    exec $*
    exit
fi
