#!/bin/bash

pre=/usr/local/encap/gnuradio-v3.8.1.0-try-2

set -x
export PYTHONPATH="${pre}/lib/python3.8/site-packages:${PYTHONPATH}"
export LD_LIBRARY_PATH="${pre}/lib:${LD_LIBRARY_PATH}"
set +x

if [ -n "$_JUST_PATHS_" ] ; then
    return
fi

if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then

    cat << EOF

      Usage: $0 PROGRAM [ARGS]

    So GNUradio can find its' python modules:
    Run PROGRAM with PYTHONPATH set to:

    $PYTHONPATH

    and LD_LIBRARY_PATH set to:

    $LD_LIBRARY_PATH

EOF

    exit 1

fi

set -x

exec $*
