#!/bin/bash

# Download and setup quickbuild

# quickbuild tag
tag=master
# Where to get quickbuild from
url=https://github.com/lanceman2/quickbuild.git

set -ex
set -o pipefail

cd "$(dirname ${BASH_SOURCE[0]})"
mkdir -p quickbuild
cd quickbuild
# github does not support git archive downloading
# so we clone the repo and then archive from the
# local clone.
[ ! -d git ] && git clone $url git
cd git

git archive --format=tar $tag | (cd .. && tar -xf -)

