#!/bin/bash

if [ "$(id -u)" != 0 ] ; then
	echo "you are not root"
	exit 1
fi

set -euxo pipefail


# Ports: Debian 9 and Ubuntu 18.04, 20.04, and 22.04
# debian 12.7

apt install -y\
 build-essential\
 libgnutls30\
 csh\
 libgtk2.0-dev\
 libgtk2.0-doc\
 libgtk-3-dev\
 libgtk-3-doc\
 devhelp\
 sox\
 at\
 imagemagick-doc\
 imagemagick\
 graphviz-dev\
 curl\
 pkgconf\
 autoconf\
 libtool\
 automake\
 locate\
 libgnutls28-dev\
 glibc-doc\
 htop\
 net-tools\
 wget\
 rsync\
 bash-completion\
 fonts-freefont-otf\
 libtree\
 gdb\
 cmake\
 libgbm-dev\
 libdecor-0-dev\
 libxml2-dev


dpkg --add-architecture i386
apt update

apt install -y\
 gcc-multilib\
 libstdc++6:i386\
 libgcc1:i386\
 zlib1g:i386\
 libncurses5:i386
