#!/bin/bash

if [ "$(id -u)" != 0 ] ; then
	echo "you are not root"
	exit 1
fi

set -euxo pipefail


# Ports: Debian 9 and Ubuntu 18.04 and 20.04

echo "Do not run this script, it breaks Ubuntu 20.04 system."
echo -e "\nMaybe: See what this does and run stuff interactively."

exit 0

dpkg --add-architecture i386
apt update

apt install -y\
 build-essential\
 gcc-multilib\
 libgnutls30\
 csh\
 libstdc++6:i386\
 libgcc1:i386\
 zlib1g:i386\
 libncurses5:i386\
 libgtk2.0-dev\
 libgtk2.0-doc\
 libgtk-3-dev\
 libgtk-3-doc\
 devhelp\
 sox\
 at\
 imagemagick-doc\
 imagemagick\
 graphviz-dev\
 curl\
 pkgconf\
 autoconf\
 libtool\
 automake\
 locate\
 libgnutls28-dev\
 youtube-dl\
 glibc-doc
