#!/bin/bash

# Dependences:
# apt install fpc lazarus

# This script installs Castle Game Engine from a zip binary

# We tried to install it from github source but it became clear that its'
# build system is pretty fucked up.  They do some pretty stupid shit like
# checking in binary dll files into the git repo.  So given they do shit
# that is that fucking stupid, there is not much hope in making a it
# from source proper.  So this is a fuck-it what-ever, I get paid to do
# this stupid bullshit.

tag=6.5-linux-x86_64

name=castle-engine

tarname=${name}-${tag}

tarfile=${tarname}.zip


# Who knows how long this url will be good for?:
url=https://github.com/$name/$name/releases/download/snapshot/${tarfile}

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"


prefix=/usr/local/encap/${tarname}


try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"



sha512sum=

case "$tag" in
    6.5-linux-x86_64)
        sha512sum="124ebd611ed546a22cd99f894a2f177b\
f4ec866e68dedbf093fcfb2cd6984e20f2d9465e317d22983aa\
f1d6ed16b428e5231df8a1d93ba7cd030fe3bc823cac6"
        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget --no-check-certificate $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi


mkdir "$builddir"
cd "$builddir"
unzip -d $PWD ../$tarfile

rm -rf $prefix

cp -a castle_game_engine $prefix

cd -

set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF

exit 0


# Feeble attempts at building from source.
#export FPCDIR=$globalunitdir

export CASTLE_FPC_OPTIONS="-I$PWD/src/base"
export CASTLE_BUILD_TOOL_OPTIONS="--compiler-option=${CASTLE_FPC_OPTIONS}"

make PREFIX=$prefix FPCDIR=$globalunitdir

make install PREFIX=$prefix FPCDIR=$globalunitdir


#fpc fpmake.pp
#
#./fpmake --globalunitdir=$globalunitdir
#
#./fpmake install\
# --globalunitdir=$globalunitdir\
# --prefix=$prefix
#
# This does not appear to be necessary.
# --baseinstalldir=$prefix/base

