#!/bin/bash


tag=release-1.4.2

tarname=fltk-$tag

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"

url=https://github.com/fltk/fltk/tarball/$tag

prefix=/usr/local/encap/$tarnameTry

tarfile=$tarname.tar.gz

sha512sum=

case "$tag" in
    release-1.4.2)
        sha512sum=
        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi


mkdir "$builddir"
cd "$builddir"
tar --strip-components=1 -xzf ../$tarfile

cmake . -B BUILD -DCMAKE_INSTALL_PREFIX:PATH="${prefix}"
cmake --build BUILD
cmake --install BUILD

cd -

set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF

