#!/bin/bash

# 2.64.6 seems to be compatible with gobject-introspection-1.71.0

ta=2.83
tag=${ta}.2
name=glib
tarname=$name-$tag

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"



url=https://download.gnome.org/sources/$name/$ta/${tarname}.tar.xz

prefix=/usr/local/encap/$tarnameTry
tarfile=$tarname.tar.xz

sha512sum=


case "$tag" in
    2.83.2)
        sha512sum=1686ef719122d2b3e8bcc569\
ba1e125cde51fbe645811e1eb7ddd49e300ff834ee\
d712bb619bba13629f23ad5f801fdc2d37e3103b51\
50ad3cb7ff9d1168d902
        ;;

    2.70.4)
        sha512sum=
        ;;
    2.71.2)
        sha512sum=21b7076c21b9a7c4ff937a\
58e3b1d05a3d351a74dec3d40674d0e3069d05b5\
7e072efad5c3b23332bd6d2098bc2960dd2de5d4\
3757a27346a6bc30a3ffce9cd1
        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget --no-check-certificate $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi


mkdir "$builddir"
cd "$builddir"
tar --strip-components=1 -xJf ../$tarfile


meson _build --prefix $prefix
ninja -C _build
ninja -C _build install


cd -

set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF

