#!/bin/bash


# apt install libcodec2-dev libgsm1-dev libqt5opengl5-dev

# sudo apt install log4cpp: FAILs installed log4cpp from source.

# pip3 install bs4 cycler decorator html5lib lxml matplotlib networkx pygraphviz pyparsing scipy sip subprocess32 tz zmq qtgui pyyaml pygi pycairo 

tag=v3.8.1.0

tarname=gnuradio-$tag

volktarfile=volk-v2.3.0.tar.gz

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"
topdir=$PWD

try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"


url=https://github.com/gnuradio/gnuradio/tarball/$tag

prefix=/usr/local/encap/$tarnameTry

tarfile=$tarname.tar.gz

sha512sum=

case "$tag" in
    v3.8.1.0)
        sha512sum=
        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi

mkdir "$builddir"
cd "$builddir"

tar --strip-components=1 -xzf ../$tarfile


mkdir -p volk
cd volk
tar --strip-components=1 -xzf $topdir/$volktarfile
cd -

mkdir BUILD
cd BUILD


cmake .. -G"Unix Makefiles"\
 -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3\
 -DCMAKE_INSTALL_PREFIX:PATH="${prefix}"\
 -DCMAKE_INSTALL_RPATH:PATH="${prefix}/lib:/usr/local/lib"\
 -DENABLE_PYTHON=true\
 -DENABLE_GRC=true\
 -DENABLE_GR_FFT=true\
 -DENABLE_GR_UTILS=true\
 -DENABLE_GRC=true\
 -DENABLE_GR_WXGUI=true\
 -DENABLE_GR_QTGUI=true\
 -DENABLE_GR_UTILS=true\
 -DENABLE_GR_UHD=true\
 -DENABLE_GR_WXGUI=true\
 -DENABLE_GR_ZEROMQ=true\
 -DENABLE_DEFAULT=true\
 -DENABLE_DOXYGEN:BOOL=true\
 -DENABLE_GR_CTRLPORT=true\
 -DENABLE_PERFORMANCE_COUNTERS=true\
 -DENABLE_INTERNAL_VOLK=ON

 #-DGNURADIO_RUNTIME_PYTHONPATH="${prefix}/lib/python3/dist-packages/gnuradio:${prefix}/lib/python3/dist-packages/gnuradio/gr:${prefix}/lib/python3/dist-packages/gnuradio/uhd"\
 #-DGR_RUNTIME_PYTHONPATH="${prefix}/lib/python3/dist-packages/gnuradio:${prefix}/lib/python3/dist-packages/gnuradio/gr:${prefix}/lib/python3/dist-packages/gnuradio/uhd"\

exit

make VERBOSE=1 -j10
make install

set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF

exit

- ######################################################
-- # Gnuradio enabled components                         
-- ######################################################
--   * testing-support
--   * python-support
--   * volk
--   * doxygen
--   * gnuradio-runtime
--   * gr-ctrlport
--   * gnuradio-companion
--   * gr-blocks
--   * gr-fec
--   * gr-fft
--   * gr-filter
--   * gr-analog
--   * gr-digital
--   * gr-dtv
--   * gr-audio
--   * * alsa
--   * * oss
--   * gr-channels
--   * gr-trellis
--   * gr-uhd
--   * gr-utils
--   * gr-vocoder
-- 
-- ######################################################
-- # Gnuradio disabled components                        
-- ######################################################
--   * sphinx
--   * gr-qtgui
--   * gr_modtool
--   * gr-video-sdl
--   * gr-wavelet
--   * gr-zeromq


