#!/bin/bash


ta=1.70
tag=${ta}.0
name=gobject-introspection


tarname=$name-$tag

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"


url=https://download.gnome.org/sources/$name/$ta/${tarname}.tar.xz

prefix=/usr/local/encap/$tarnameTry
tarfile=$tarname.tar.xz

sha512sum=

case "$tag" in
    1.71.0)
        sha512sum=

        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget --no-check-certificate $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi


mkdir "$builddir"
cd "$builddir"
tar --strip-components=1 -xJf ../$tarfile



meson _build --prefix $prefix

cd _build
#meson compile
#meson install

ninja
ninja install


set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF

