#!/bin/bash

#To get a list of what broken:
# cd BUILD && cmake .. -LAH > xxx

############################ DEPENDENCIES #########################################


tag=v0.2.1

tarname=gr-osmosdr-$tag

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"


url=https://github.com/osmocom/gr-osmosdr/tarball/$tag

prefix=/usr/local/encap/$tarnameTry

tarfile=$tarname.tar.gz

sha512sum=

case "$tag" in
    v0.2.1)
        sha512sum=
        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget --no-check-certificate $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi

mkdir "$builddir"
cd "$builddir"

tar --strip-components=1 -xzf ../$tarfile


mkdir BUILD
cd BUILD

cmake .. -G"Unix Makefiles"\
 -DCMAKE_INSTALL_PREFIX:PATH="${prefix}"\


make VERBOSE=1 -j10
make install

set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF
