#!/bin/bash

#https://docs.gtk.org/gtk4/building.html#dependencies

# DEPENDENCIES
#
# pip3 install meson
#
# apt install libgraphene-1.0-dev shared-mime-info libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev
#
# ninja glib gdk-pixbuf pango gobject-introspection libepoxy
#



ta=4.6
tag=${ta}.1
name=gtk


tarname=$name-$tag

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"



url=https://download.gnome.org/sources/$name/$ta/${tarname}.tar.xz

prefix=/usr/local/encap/$tarnameTry
tarfile=$tarname.tar.xz

sha512sum=

case "$tag" in
    4.6.1)
        sha512sum=
        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget --no-check-certificate $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi


mkdir "$builddir"
cd "$builddir"
tar --strip-components=1 -xJf ../$tarfile



meson _build --prefix $prefix

cd _build
ninja
ninja install


set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF
