#!/bin/bash


tag=hdf5_1.14.5

tarname=hdf5-$tag

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"


url=https://github.com/HDFGroup/hdf5/tarball/$tag
prefix=/usr/local/encap/$tarnameTry

tarfile=$tarname.tar.gz

sha512sum=


case "$tag" in
    hdf5_1.14.5)
        sha512sum=
        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget --no-check-certificate $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi

mkdir "$builddir"
cd "$builddir"

tar --strip-components=1 -xzf ../$tarfile

mkdir BUILD
cd BUILD

cmake .. -G"Unix Makefiles"\
 -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE\
 -DCMAKE_INSTALL_PREFIX:PATH="${prefix}"\
 -DCMAKE_INSTALL_RPATH:PATH="${prefix}/lib"\
 -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=TRUE


make VERBOSE=1 -j $(nproc)
make install

set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF
