#!/bin/bash


tag=2.3.8

tarname=motif-$tag

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"

url=https://sourceforge.net/projects/motif/files/Motif%202.3.8%20Source%20Code/motif-2.3.8.tar.gz/download

prefix=/usr/local/encap/$tarnameTry

tarfile=$tarname.tar.gz

sha512sum=

case "$tag" in
    2.3.8)
        sha512sum=
        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi


mkdir "$builddir"
cd "$builddir"
tar --strip-components=1 -xzf ../$tarfile

./configure --prefix=$prefix
make -j 10
make install


cd -

set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF

