#!/bin/bash

# Notes on Dependencies:

# package libeditline-dev was too old
# So we installed it from source using script editline
#
# In addition we APT installed:
#
# apt install curl libssl-dev libbrotli-dev \
libbz2-dev liblzma-dev libcurl4-openssl-dev \
libsqlite3-dev libboost-all-dev \
xml-core bison flex libseccomp-dev libgc-dev


tag=2.3.7

tarname=nix-$tag

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"
url=https://nixos.org/releases/nix/$tarname/$tarname.tar.xz
#url=https://github.com/NixOS/nix/tarball/$tag

prefix=/usr/local/encap/$tarnameTry

tarfile=$tarname.tar.xz
#tarfile=$tarname.tar.gz

sha512sum=

case "$tag" in
    2.3.7)
        sha512sum=
        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget --no-check-certificate $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi

mkdir "$builddir"
cd "$builddir"
tar --strip-components=1 -xJf ../$tarfile
#tar --strip-components=1 -xzf ../$tarfile


#set +e
#autoreconf -vi
#set -e
#autoreconf -vi

./configure --prefix=$prefix --enable-gc
make -j5
make install

set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF
