#!/bin/bash

# apt install git cmake build-essential libgl1-mesa-dev libxt-dev\
 qt5-default libqt5x11extras5-dev libqt5help5 qttools5-dev\
 qtxmlpatterns5-dev-tools libqt5svg5-dev libopenmpi-dev libtbb-dev\
 ninja-build

# Needed a newer version or cmake for on systems with Ubuntu 18.04,
# so we built and installed cmake from source.

# We installed python3 from source using script in this dir, then:
# pip3 install numpy openpmd_api


# Looks like there is no way to get a tarball directly from a server.  We
# end up downloading much more data that is not necessary for building the
# software package.


tag=v5.9.0

tarname=paraview-git-$tag

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

try=0
tarnameTry=${tarname}-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=${tarname}-try-$try
done
builddir="${tarnameTry}"


url=https://gitlab.kitware.com/paraview/paraview.git


prefix=/usr/local/encap/$tarnameTry


if [ ! -e $tarname ] ; then
    git clone $url $tarname
    cd $tarname
    git checkout $tag
    git submodule update --init --recursive
    cd -
fi

# It'd be nice to have a way to know that the build try does not change
# the source code.  We check with "git status" after.

mkdir "$builddir"
cd "$builddir"


# WTF is:      load the “VR Plugin” 


# We installed cmake from source and cmake from source sucks,
# therefore (the writers of cmake are dumb fucks):
export CMAKE_ROOT=/usr/share/cmake


# If we have nvidia cards and drivers ???
#-DPARAVIEW_ENABLE_NVPIPE=ON\

cmake\
 -GNinja\
 -DPARAVIEW_USE_PYTHON=ON\
 -DPARAVIEW_USE_MPI=ON\
 -DVTK_SMP_IMPLEMENTATION_TYPE=TBB\
 -DCMAKE_BUILD_TYPE=Release\
 -DBUILD_SHARED_LIB=ON\
 -DPARAVIEW_BUILD_QT_GUI=ON\
 -DCMAKE_INSTALL_PREFIX:PATH="${prefix}"\
 -DCMAKE_INSTALL_RPATH:PATH="${prefix}/lib"\
 -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=TRUE\
 -DPARAVIEW_USE_MPI=ON\
 -DPARAVIEW_PLUGIN_VRPlugin_USE_VRPN=ON\
 -DPARAVIEW_PLUGIN_VRPlugin_USE_VRUI=ON\
 -DPARAVIEW_BUILD_PLUGIN_VRPlugin=ON\
 -DPARAVIEW_ENABLE_VISITBRIDGE=ON\
 -DPARAVIEW_ENABLE_NVPIPE=OFF\
 -DPARAVIEW_ENABLE_GDAL=OFF\
 -DPARAVIEW_ENABLE_LAS=OFF\
 -DPARAVIEW_ENABLE_OPENTURNS=OFF\
 -DPARAVIEW_ENABLE_PDAL=OFF\
 -DPARAVIEW_ENABLE_MOTIONFX=OFF\
 -DPARAVIEW_ENABLE_MOMENTINVARIANTS=OFF\
 -DPARAVIEW_ENABLE_LOOKINGGLASS=OFF\
 -DPARAVIEW_ENABLE_XDMF2=ON\
 -DPARAVIEW_ENABLE_XDMF3=ON\
 -DPARAVIEW_ENABLE_FFMPEG=OFF\
 -DPARAVIEW_ENABLE_COSMOTOOLS=OFF\
 -DPARAVIEW_USE_VRPN=ON\
 -DVRPN_INCLUDE_DIR=/usr/local/include\
 -DVRPN_LIBRARY_DIR=/usr/local/lib\
 ../$tarname

exit

ninja -v -j 40
ninja -v install

cd -


set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF
