#!/bin/bash

tag=0.43.4

tarname=pixman-$tag

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"

url=https://www.cairographics.org/releases/${tarname}.tar.gz

prefix=/usr/local/encap/$tarnameTry

tarfile=$tarname.tar.gz

sha512sum=

case "$tag" in
    0.43.4)
        sha512sum=
        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget --no-check-certificate $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi

mkdir "$builddir"
cd "$builddir"
tar --strip-components=1 -xzf ../$tarfile

mkdir BUILD
cd BUILD

meson setup ..\
 --prefix=$prefix\
 --libdir=$prefix/lib\
 --includedir=$prefix/include\
 --libexecdir=$prefix/lib\
 --bindir=$prefix/bin\
 --buildtype=debug

ninja
ninja install

cd -

set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF

