#!/bin/bash

#Dependencies:
# apt install\
 libbluetooth-dev\
 libbz2-dev\
 libdb-dev\
 libexpat1-dev\
 libffi-dev\
 libgdbm-dev\
 liblzma-dev\
 libmpdec-dev\
 libncursesw5-dev\
 libreadline-dev\
 libsqlite3-dev\
 libssl-dev\
 zlib1g-dev\
 libbz2-dev

# From here: openssl

set -ex

if [ ! -e /usr/local/lib/libssl.so ] ; then
    echo "Install openssl first"
    exit 1
fi

# Find a python release that works:
tag=3.9.1
#tag=3.8.3
#tag=3.8.1
#tag=3.7.6

tarname=Python-$tag

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"


#https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tar.xz
url=https://www.python.org/ftp/python/$tag/$tarname.tar.xz

prefix=/usr/local/encap/$tarnameTry

tarfile=$tarname.tar.xz

sha512sum=

case "$tag" in
    3.9.1)
        sha512sum=b90029d6825751685983e9dcf0e\
0ec9e46f18e6c7d37b0dd7a245a94316f8c0090308ad7\
c2b2b49ed2514b0b909177231dd5bcad03031bf4624e3\
7136fcf8019
        ;;
    3.8.3)
        sha512sum=3103bd8d944f3905eee3a2b52fd1\
f5c7dee380f9c5a99ad35a401fcba5a9117c3860ecec5c\
b47a92712c6549442fd2fa553a15c5657241dd09f5d00b\
9ed4f0f4
        ;;

    3.7.6)
        sha512sum=5be022c384728b0c6709d165486f6\
6226d126c521b466ed24d0c4c3c5910ec786a734f4c2c91\
6ac409213c54a492b9fb230fb721c41e3de281676a7e9d8\
f3171
        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget $url --no-check-certificate -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi


mkdir "$builddir"
cd "$builddir"
tar --strip-components=1 -xJf ../$tarfile


# The --with-ssl=/usr/local/lib seems to fix the pip install
# errors that have:
#
#  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError('No cipher can be selected.'))': /simple/pip/

CFLAGS="-g -Wall"\
 ./configure\
 --prefix=$prefix\
 --enable-shared\
 --with-ssl=/usr/local/lib

make -j $(nproc)
make install

cd -

set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF
