#!/bin/bash

tag=6.80

tarname=scc-$tag

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

sha512sum=

case ${tag} in

    6.80)
        sha512sum=648d0a0a95fd41b29a9fa268e9ed0\
e63a421519c6a015824404a1af5b2658ba33282548fc684\
f09b83c5f485fa380981754876408f1e3171aaa20f7e73645026
        ;;
esac


try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"

url="https://github.com/jleffler/scc-snapshots/tarball/release/$tag"


prefix=/usr/local/encap/$tarnameTry

tarfile=$tarname.tar.gz


if [ ! -e "$tarfile" ] ; then
    wget --no-check-certificate $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi

mkdir "$builddir"
cd "$builddir"
tar --strip-components=1 -xzf ../$tarfile


make

mkdir -p $prefix/bin

cp scc $prefix/bin/jleffler_scc


cd -

set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix/bin/jleffler_scc

EOF
