#!/bin/bash


tag=3.16.1

tarname=valgrind-$tag

set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"


url=https://sourceware.org/pub/valgrind/$tarname.tar.bz2

prefix=/usr/local/encap/$tarnameTry

tarfile=$tarname.tar.xz

sha512sum=

case "$tag" in
    3.16.1)
        sha512sum=2a4173efe1b6facdd2f5c5ee8e\
d006704168eba1813736fccc8191d60363afd9619751\
2cf42037e65f18d4ddd49adc74a54c47210df216fba3\
c46bf68ef0f950
        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget --no-check-certificate $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi

mkdir "$builddir"
cd "$builddir"
tar --strip-components=1 -xjf ../$tarfile


./configure --prefix=$prefix --with-mpicc=none
make -j5
make install

cd -

set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF

