#!/bin/bash


#tag=master

tag=2169643d7d47869098f58d372bd0fcf8ec8d1eaf

tarname=wsServer-2169


set -exo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"

try=0
tarnameTry=$tarname-try-$try
while [ -d "${tarnameTry}" ] ; do
    let try=$try+1
    tarnameTry=$tarname-try-$try
done
builddir="${tarnameTry}"

url=https://github.com/Theldus/wsServer/tarball/$tag

prefix=/usr/local/encap/$tarnameTry

tarfile=$tarname.tar.gz

sha512sum=

case "$tag" in
    2169643d7d47869098f58d372bd0fcf8ec8d1eaf)
        sha512sum=
        ;;
esac


if [ ! -e "$tarfile" ] ; then
    wget --no-check-certificate $url -O $tarfile
fi


if [ -n "$sha512sum" ] ; then
    echo "$sha512sum  $tarfile" | sha512sum -c -
else
    set +x
    sha512sum $tarfile
    set -x
fi

mkdir "$builddir"
cd "$builddir"
tar --strip-components=1 -xzf ../$tarfile

libdir=$prefix/lib

make PREFIX=$prefix LIBDIR=$libdir
make install PREFIX=$prefix LIBDIR=$libdir

cd -

set +x

cat << EOF

   SUCCESSFULLY installed $tarname in $prefix

EOF
